<?php

namespace AppBundle\Repository;

/**
 * AlarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmRepository extends \Doctrine\ORM\EntityRepository
{
}
