<?php

namespace AppBundle\Repository;

/**
 * AlarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastFiveAlarms($customer){

        $queryBuilder = $this->createQueryBuilder('a')
            ->where('a.customer = :customer')
            ->setParameter('customer', $customer)
            ->setMaxResults(5)
            ->orderBy('a.id', 'DESC');
        return $queryBuilder->getQuery()->getResult();
    }

}
