<?php

namespace AppBundle\Repository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastFiveLogs($customer){

        $queryBuilder = $this->createQueryBuilder('l')
            ->where('l.customer = :customer')
            ->setParameter('customer', $customer)
            ->setMaxResults(5)
            ->orderBy('l.id', 'DESC');
        return $queryBuilder->getQuery()->getResult();
    }

}
