<?php

namespace AppBundle\Repository;

/**
 * recordingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recordingRepository extends \Doctrine\ORM\EntityRepository
{
}
