<?php

namespace AppBundle\Repository;

/**
 * recordingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneById($id,$customer){

        $queryBuilder = $this->createQueryBuilder('r')
            ->where('r.id = :id')
            ->setParameter('id', $id)
            ->andWhere('r.customer = :customer')
            ->setParameter('customer', $customer)
            ->setMaxResults(1);
        return $queryBuilder->getQuery()->getOneOrNullResult();
    }


    public function getRecordings($customer){

        $queryBuilder = $this->createQueryBuilder('r')
            ->where('r.customer = :customer')
            ->setParameter('customer', $customer)
            ->orderBy('r.id', 'DESC');
        return $queryBuilder->getQuery()->getResult();
    }

}
